### ISSUE TITLE
Pod didn't find available persistent volumes to bind.

### ISSUE THREAD

**Issue by belfortmaycon** [ibm-watson-iot/iot-docs#18]
I'm executing the installer on a local open shift cluster and getting this message on Pod Manager.
> 0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.

Here are some outputs from the troubleshooting section
```
➜  oc describe po/mas-mongo-ce-0 -n mongo

Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  4s (x9 over 5m50s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
```
```
➜  oc describe pvc/data-volume-mas-mongo-ce-0
Name:          data-volume-mas-mongo-ce-0
Namespace:     mongo
StorageClass:  local-storage
Status:        Pending
Volume:        
Labels:        app=mas-mongo-ce-svc
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       mas-mongo-ce-0
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  WaitForFirstConsumer  7m7s                  persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  WaitForPodScheduled   72s (x25 over 6m57s)  persistentvolume-controller  waiting for pod mas-mongo-ce-0 to be scheduled
```
```
➜  oc get storageclass
NAME            PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-storage   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  18h
```
```
➜  echo $MONGODB_STORAGE_CLASS
local-storage
```
```
➜  oc get crd/mongodbcommunity.mongodbcommunity.mongodb.com
NAME                                            CREATED AT
mongodbcommunity.mongodbcommunity.mongodb.com   2022-04-22T15:06:15Z

➜  oc get role mongodb-kubernetes-operator
NAME                          CREATED AT
mongodb-kubernetes-operator   2022-04-22T15:06:16Z

➜  oc get rolebinding mongodb-kubernetes-operator
NAME                          ROLE                               AGE
mongodb-kubernetes-operator   Role/mongodb-kubernetes-operator   11m

➜  oc get serviceaccount mongodb-kubernetes-operator
NAME                          SECRETS   AGE
mongodb-kubernetes-operator   2         12m
```
```
oc get MongoDBCommunity -n mongo -o yaml
[...]
        volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: local-storage
        - metadata:
            name: logs-volume
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: local-storage
[...]
```
I hope someone can help me with this issue.

Thank you
